package com.ledgerflow.core.synthetic;

public enum DifficultyTag {
    DUPLICATE_TRANSACTION,
    DUPLICATE_INVOICE,
    PARTIAL_PAYMENT,
    MULTI_INVOICE_PAYMENT,
    IDENTICAL_INVOICE_AMOUNTS,
    CUSTOMER_NAME_VARIATION,
    LATE_PAYMENT,
    INTERNAL_TRANSFER,
    AMBIGUOUS_MERCHANT,
    REFUND,
    SUBSCRIPTION_INCREASE,
    MISSING_INVOICE,
    UNMATCHED_PAYMENT,
    UNUSUAL_VENDOR
}
